### ISSUE TITLE
Imager en Linux

### ISSUE THREAD

**Issue by CarlosCCC9** [bitcoinR3search/BitcoinResearch#3]
Mii otra maquina tiene linux y el adaptador SD si funciona. El problema aqui es instalar el imager, de la pagina se descarga un archivo .deb pero no me deja isntalar con apt install. Usando snap tarda mucho

**Comment by jpcrespo** [comment]
ok. Mira intenta probar con este comando:

**Comment by jpcrespo** [comment]
sudo apt install ./version imager.deb

es lo que funcionó en todo caso.
